### ISSUE TITLE
open existing notebook 

### ISSUE THREAD

**Issue by nimaone** [abhishekkrthakur/colabcode#21]
open existing notebook in  google drive is not working..
any suggestion?

**Comment by Skander-hadjromdhan** [comment]
Did you wait for the extensions to load? are you seeing the source code of the notebooks? If yes, look at the bar in the bottom of the editor and wait till extensions are loaded. After that, the notebooks will be displayed.

![im1](https://user-images.githubusercontent.com/37614760/93071743-ce8fd180-f680-11ea-85df-3f02a85d53a0.png)

In this first image, you will see my existing notebook in google drive is not loaded properly because the extensions were loading

![im2](https://user-images.githubusercontent.com/37614760/93071804-e1a2a180-f680-11ea-8760-e38fa5ee8d8d.png)

In this second image, after waiting for 40 seconds (approx) The notebook was opened properly.

**Comment by nimaone** [comment]
> Did you wait for the extensions to load? are you seeing the source code of the notebooks? If yes, look at the bar in the bottom of the editor and wait till extensions are loaded. After that, the notebooks will be displayed.
> 
> ![im1](https://user-images.githubusercontent.com/37614760/93071743-ce8fd180-f680-11ea-85df-3f02a85d53a0.png)
> 
> In this first image, you will see my existing notebook in google drive is not loaded properly because the extensions were loading
> 
> ![im2](https://user-images.githubusercontent.com/37614760/93071804-e1a2a180-f680-11ea-8760-e38fa5ee8d8d.png)
> 
> In this second image, after waiting for 40 seconds (approx) The notebook was opened properly. I sometimes have to close the notebook and reopen it after the extensions are loaded

Yes you are right..
I'm realizing that my exetention doesn't working
I'm waiting for it so much time but not connected to runtime
