### ISSUE TITLE
Getting Too many connections error on running

### ISSUE THREAD

**Issue by aryamansriram** [abhishekkrthakur/colabcode#23]
Hi,
I am encountering the following error when I try to run colabcode

`
Too many connections! The tunnel session 'ts_1haqep9AXrK0M55zyQFF0HgWbVH' has violated the rate-limit policy of 20 connections per minute by initiating 36 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702
`
Kindly suggest how to resolve it.

**Comment by Skander-hadjromdhan** [comment]
This error is due to NGROK and as this was made using the free version. You may have this issue if you reload Code-Server (The VSCode Web IDE). You can wait (a little) and refresh. This resolves the error. Here is a StackOverflow post about the same error: https://stackoverflow.com/questions/40939587/ngrok-err-ngrok-702-too-many-connections.

**Comment by aryamansriram** [comment]
Thanks for that, closing the issue as it worked for me

**Comment by TanayKarve** [comment]
Fixed in #29 
Please merge
