### ISSUE TITLE
Too many connections! The tunnel session 'ts_1hlqlpmaWrbJN1bOTucLT1dsx2M'

### ISSUE THREAD

**Issue by hiteshhedwig** [abhishekkrthakur/colabcode#25]
Too Many Connections

Too many connections! The tunnel session 'ts_1hlqlpmaWrbJN1bOTucLT1dsx2M' has violated the rate-limit policy of 20 connections per minute by initiating 26 connections in the last 60 seconds. Please decrease your inbound connection volume or upgrade to a paid plan for additional capacity.

The error encountered was: ERR_NGROK_702

What does this even mean?
I tried using code server as always. Throws unprecedented error.

**Comment by Skander-hadjromdhan** [comment]
Same as an old issue #23 .
(https://github.com/abhishekkrthakur/colabcode/issues/23)

**Comment by ahtyamovdanil** [comment]
fixed it in #36 
Get authorization token from "Setup & Installation" tab in your ngrok account and pass it to `authtoken` argument

**Comment by carlosh93** [comment]
> fixed it in #36
> Get authorization token from "Setup & Installation" tab in your ngrok account and pass it to `authtoken` argument

Hello! When I add my token into the authtoken argument, I get the message "Tunnel xxxxxxxxx.ngrok.io not found". Do you have any advice?

**Comment by darkshadow013** [comment]
This is because ngrok tunnel is created using free account which gives limit to make 20 api requests per minute.

You can try this on your local machine for more detail with :

`
1. sudo snap install ngrok
2. jupyter notebook
3. ngrok http 8888`

You will see number of requests made and when it exceeds limit of 20 the error you are facing will occur.

I hope it will help you understand clear picture of this problem.
