### ISSUE TITLE
Extensions don't seem to work and the Python Interpreter fails to get activated

### ISSUE THREAD

**Issue by anusikh** [abhishekkrthakur/colabcode#50]
Can't manually select the Python Interpreter as well

**Comment by pablovela5620** [comment]
Having the same issue, looks like this could be a solution https://github.com/cdr/code-server/issues/1818

**Comment by amankhandelia** [comment]
For future readers,

As @pablovela5620 suggested, the issue is with the code server and python extension not working in conjunction, however you can easily solve the same by downgrading the python extension to v2020.5.86806, also note that the extension and other features will malfunction if you are not accessing the ngrok url over https, by default the url printed out is http, just add an s, it will save you a lot trouble, also if anybody finds a programmatic way to downgrade vscode extension, do let me know

**Comment by anusikh** [comment]
How do you downgrade the extensions? Do we need to separately download the VSIX files?

**Comment by amankhandelia** [comment]
@anusikh, refer to this
https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version/53755378
